repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.11.0 # Choose a version
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Choose a version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0 # Choose a version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-print]
        # E501: line too long (handled by black)
        # W503: line break before binary operator (black prefers this)
        args: ['--ignore=E501,W503']

  - repo: https://github.com/pre-commit/mirrors-mypy
    # pyproject.toml の mypy バージョン "^1.10.0" に合わせる
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          # pyproject.toml で直接依存関係にある pydantic の型ヒントを明示
          - pydantic
          # pyproject.toml の dev 依存関係に定義されている型スタブ
          - types-PyYAML
          - types-redis
          - types-cachetools
        # mypy の除外パスを pyproject.toml の設定と整合させる
        # (docs/, notebooks/ は pyproject.toml にも記載あり)
        exclude: ^(docs/|notebooks/|tests/fixtures/)
        args: [--strict, --ignore-missing-imports] # 型チェックの厳格化

  # safety は公式の pre-commit ミラーが存在しないため、local フックとして設定する
  - repo: local
    hooks:
      - id: safety
        name: Run Safety Security Check
        # Poetry 環境で safety check コマンドを実行
        entry: poetry run safety check
        # 環境の Python を使用
        language: system
        # safety はファイル名を引数として受け取らないため、false に設定
        pass_filenames: false
        # pyproject.toml または poetry.lock が変更された場合にのみフックを実行
        files: '^(pyproject\.toml|poetry\.lock)$'
        # 前回の設定を維持: 特定の脆弱性を無視する場合
        args: ["--ignore=51457"]