global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fx_trader'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: fx_trader

  - job_name: 'broker'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/broker/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: broker

  - job_name: 'data_feeds'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/data/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: data_feeds

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: redis

  - job_name: 'minio'
    static_configs:
      - targets: ['localhost:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: minio

  - job_name: 'vault'
    static_configs:
      - targets: ['localhost:8200']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: vault

  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: mlflow

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alert_rules/*.yml'
