from feast import FileSource, ValueType
from feast.types import Float32, Int64, String, UnixTimestamp

# Define the schema for your raw price data (OHLCV)
# This should match the columns in your price_data.parquet file
price_data_schema = [
    ("event_timestamp", UnixTimestamp),  # Timestamp of the candle
    ("currency_pair_id", String),       # e.g., "EUR_USD"
    ("open", Float32),
    ("high", Float32),
    ("low", Float32),
    ("close", Float32),
    ("volume", Int64),
]

# Data source for historical price data
price_data_source = FileSource(
    name="price_ohlcv_source",
    # Path relative to feature_store.yaml, e.g., feature_store/data/price_data.parquet
    path="data/price_data.parquet",
    timestamp_field="event_timestamp",
    description="Historical OHLCV price data for currency pairs",
    # schema=price_data_schema, # Explicit schema definition is good practice
    # created_timestamp_column="created_timestamp", # Optional: if you have a column indicating when the row was created
)

# Define the schema for your raw macro-economic data
macro_data_schema = [
    ("event_timestamp", UnixTimestamp),
    ("country_code", String),  # e.g., "US", "EU", "JP"
    ("indicator_name", String),  # e.g., "CPI", "INTEREST_RATE"
    ("value", Float32),
]

# Data source for macro-economic indicators
macro_data_source = FileSource(
    name="macro_economic_source",
    path="data/macro_data.parquet",  # e.g., feature_store/data/macro_data.parquet
    timestamp_field="event_timestamp",
    description="Macro-economic indicators like CPI, interest rates",
    # schema=macro_data_schema,
)

# Define the schema for your raw news sentiment data
news_sentiment_schema = [
    ("event_timestamp", UnixTimestamp),
    ("currency_pair_id", String),  # Or a more general 'asset_id' or 'topic'
    ("sentiment_score", Float32),
    ("relevance_score", Float32),
    ("news_source", String),  # Optional: source of the news
]

# Data source for news sentiment scores
news_sentiment_source = FileSource(
    name="news_sentiment_source",
    # e.g., feature_store/data/news_sentiment.parquet
    path="data/news_sentiment.parquet",
    timestamp_field="event_timestamp",
    description="News sentiment scores related to currency pairs or relevant topics",
    # schema=news_sentiment_schema,
)

# Note: The actual Parquet files (price_data.parquet, macro_data.parquet, news_sentiment.parquet)
# would need to be generated by your data ingestion and validation pipeline and placed in the
# `fx_trader/feature_store/data/` directory.
